name: trigger-gitlab-ci
run-name: ${{ github.event_name }} triggered by ${{ github.actor }}

on: [push]

jobs:
  trigger-gitlab-ci:
      runs-on: ubuntu-latest
      steps:
          - name: Trigger CI
            run: curl -X POST --fail -F token=${{ secrets.TRIGGER_GITLAB_CI }} -F ref=main https://gitlab.com/api/v4/projects/42797718/trigger/pipeline
